CREATE TABLE BAKERYINFO_TB
(
    id       INT              NOT NULL, 
    brand    VARCHAR2(300)    NOT NULL, 
    CONSTRAINT BAKERYINFO_TB_PK PRIMARY KEY (id)
)
/
CREATE TABLE BAKERY_TB
(
    no      INT              NOT NULL, 
    id      INT              NOT NULL, 
    name    VARCHAR2(300)    NULL, 
    addr    VARCHAR2(900)    NULL, 
    lat     NUMBER           NULL, 
    lng     NUMBER           NULL, 
    CONSTRAINT BAKERY_TB_PK PRIMARY KEY (no)
)
/

CREATE SEQUENCE BAKERY_TB_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER BAKERY_TB_AI_TRG
BEFORE INSERT ON BAKERY_TB 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT BAKERY_TB_SEQ.NEXTVAL
    INTO :NEW.no
    FROM DUAL;
END;
/

--DROP TRIGGER BAKERY_TB_AI_TRG;
/

--DROP SEQUENCE BAKERY_TB_SEQ;
/

ALTER TABLE BAKERY_TB
    ADD CONSTRAINT FK_BAKERY_TB_id_BAKERYINFO_TB_ FOREIGN KEY (id)
        REFERENCES BAKERYINFO_TB (id)
/