CREATE TABLE CINEMAINFO_TB
(
    id       INT              NOT NULL, 
    brand    VARCHAR2(300)    NOT NULL, 
    CONSTRAINT CINEMAINFO_TB_PK PRIMARY KEY (id)
)
/
CREATE TABLE CINEMA_TB
(
    no      INT              NOT NULL, 
    id      INT              NOT NULL, 
    name    VARCHAR2(300)    NULL, 
    addr    VARCHAR2(900)    NULL, 
    lat     NUMBER           NULL, 
    lng     NUMBER           NULL, 
    CONSTRAINT CINEMA_TB_PK PRIMARY KEY (no)
)
/

CREATE SEQUENCE CINEMA_TB_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER CINEMA_TB_AI_TRG
BEFORE INSERT ON CINEMA_TB 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT CINEMA_TB_SEQ.NEXTVAL
    INTO :NEW.no
    FROM DUAL;
END;
/

--DROP TRIGGER CINEMA_TB_AI_TRG;
/

--DROP SEQUENCE CINEMA_TB_SEQ;
/
ALTER TABLE CINEMA_TB
    ADD CONSTRAINT FK_CINEMA_TB_id_CINEMAINFO_TB_ FOREIGN KEY (id)
        REFERENCES CINEMAINFO_TB (id)
/