CREATE TABLE DEPTINFO_TB
(
    id       INT              NOT NULL, 
    brand    VARCHAR2(300)    NOT NULL, 
    CONSTRAINT DEPTINFO_TB_PK PRIMARY KEY (id)
)
/
CREATE TABLE DEPT_TB
(
    no      INT              NOT NULL, 
    id      INT              NOT NULL, 
    name    VARCHAR2(300)    NULL, 
    addr    VARCHAR2(900)    NULL, 
    lat     NUMBER           NULL, 
    lng     NUMBER           NULL, 
    CONSTRAINT DEPT_TB_PK PRIMARY KEY (no)
)
/

CREATE SEQUENCE DEPT_TB_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER DEPT_TB_AI_TRG
BEFORE INSERT ON DEPT_TB 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT DEPT_TB_SEQ.NEXTVAL
    INTO :NEW.no
    FROM DUAL;
END;
/

--DROP TRIGGER DEPT_TB_AI_TRG;
/

--DROP SEQUENCE DEPT_TB_SEQ;
/


ALTER TABLE DEPT_TB
    ADD CONSTRAINT FK_DEPT_TB_id_DEPTINFO_TB_id FOREIGN KEY (id)
        REFERENCES DEPTINFO_TB (id)
/

select * from dept_tb;