CREATE TABLE FASTFOODINFO_TB
(
    id       INT              NOT NULL, 
    brand    VARCHAR2(300)    NOT NULL, 
    CONSTRAINT FASTFOODINFO_TB_PK PRIMARY KEY (id)
)
/
CREATE TABLE FASTFOOD_TB
(
    no      INT              NOT NULL, 
    id      INT              NOT NULL, 
    name    VARCHAR2(300)    NULL, 
    addr    VARCHAR2(900)    NULL, 
    lat     NUMBER           NULL, 
    lng     NUMBER           NULL, 
    CONSTRAINT FASTFOOD_TB_PK PRIMARY KEY (no)
)
/

CREATE SEQUENCE FASTFOOD_TB_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER FASTFOOD_TB_AI_TRG
BEFORE INSERT ON FASTFOOD_TB 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT FASTFOOD_TB_SEQ.NEXTVAL
    INTO :NEW.no
    FROM DUAL;
END;
/

--DROP TRIGGER FASTFOOD_TB_AI_TRG;
/

--DROP SEQUENCE FASTFOOD_TB_SEQ;
/
ALTER TABLE FASTFOOD_TB
    ADD CONSTRAINT FK_FASTFOOD_TB_id_FASTFOODINFO FOREIGN KEY (id)
        REFERENCES FASTFOODINFO_TB (id)
/